import type { Json } from "@/integrations/supabase/types";

export type DashboardSummary = {
  pending_sales: number;
  pending_units: number;
  open_reconciliations: number;
  ready_to_close: number;
  open_exceptions: number;
  blocking_exceptions: number;
  unsigned_sku: number;
  active_partner_stores: number;
  closed_in_period: number;
};
export type ReconciliationRow = {
  id: string;
  partner_id: string;
  period_start: string;
  period_end: string;
  status: string;
  frequency: string;
  sales_count: number;
  units_sold: number;
  gross_amount: number;
  billable_amount: number;
  exceptions_count: number;
  created_at: string;
  closed_at: string | null;
  partner_name: string;
};
export type ReconciliationList = { rows: ReconciliationRow[]; total: number };
export type ReconciliationItem = {
  id: string;
  reconciliation_id: string;
  marketplace_sale_id: string;
  partner_id: string;
  store_id: string;
  variant_id: string | null;
  quantity: number;
  gross_amount: number;
  unit_reference_value: number | null;
  billable_amount: number | null;
  status: string;
  exception_status: string | null;
  inventory_effect_status: string;
  inventory_movement_id: string | null;
  reversed_movement_id: string | null;
  price_snapshot: { unit_price?: number; rule?: string; net_reference?: number } | null;
  error_message: string | null;
  created_at: string;
  sku: string | null;
  product_name: string | null;
  external_order_id: string;
  external_sku: string;
  store_name: string;
  marketplace: string;
  sale_date: string;
  status_label?: string;
};
export type ReconciliationException = {
  id: string;
  reconciliation_id: string | null;
  item_id: string | null;
  marketplace_sale_id: string | null;
  partner_id: string | null;
  store_id: string | null;
  variant_id: string | null;
  exception_type: string;
  severity: string;
  status: string;
  message: string;
  details: Json;
  resolution_type: string | null;
  resolution_notes: string | null;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string;
  partner_name?: string;
  store_name?: string;
  sku?: string;
};
export type ReconciliationAdjustment = {
  id: string;
  organization_id: string;
  reconciliation_id: string;
  adjustment_type: string;
  amount: number;
  reason: string;
  created_by: string;
  created_at: string;
};
export type ReconciliationDetail = ReconciliationRow & {
  partner_name?: string;
  cutoff_at: string | null;
  snapshot: {
    totals?: {
      sales?: number;
      units?: number;
      gross?: number;
      billable_items?: number;
      adjustments?: number;
      net_billable?: number;
    };
  } | null;
  items: ReconciliationItem[];
  exceptions: ReconciliationException[];
  adjustments: ReconciliationAdjustment[];
  by_sku: { sku: string | null; product_name: string | null; items: number; units: number; billable: number }[];
  by_day: { d: string; items: number; units: number; billable: number }[];
  by_marketplace: { marketplace: string; items: number; units: number; billable: number }[];
  summary: { shipped: number; reconciled: number; on_hand: number };
};
export type MarketplaceSaleRow = {
  id: string;
  store_id: string;
  sale_date: string;
  external_order_id: string;
  external_sku: string;
  external_event_id: string | null;
  variant_id: string | null;
  quantity: number;
  gross_amount: number;
  shipping_fee: number;
  discount_amount: number;
  platform_fee: number;
  currency: string;
  status: string;
  source: string;
  reconciliation_item_id: string | null;
  created_at: string;
  global_warehouse?: string;
  store_name: string;
  marketplace: string;
  ownership_type: string;
  partner_id: string | null;
  partner_name: string;
  sku?: string;
  product_name?: string;
};
export type MarketplaceSaleList = { rows: MarketplaceSaleRow[]; total: number };
export type MarketplaceStoreRow = {
  id: string;
  code: string;
  name: string;
  marketplace: string;
  marketplace_store_id: string | null;
  ownership_type: string;
  partner_id: string | null;
  status: string;
  notes: string | null;
  created_at: string;
  partner_name: string;
};
export type MarketplaceStoreList = { rows: MarketplaceStoreRow[]; total: number };
export type SkuMappingRow = {
  id: string;
  store_id: string | null;
  external_sku: string;
  variant_id: string;
  created_at: string;
  store_name: string | null;
  sku: string;
};
export type SkuMappingList = { rows: SkuMappingRow[]; total: number };
export type PriceTableRow = {
  id: string;
  code: string;
  name: string;
  status: string;
  valid_from: string;
  valid_to: string | null;
  notes: string | null;
  created_at: string;
  items_count: number;
  partners_count: number;
};
export type PriceTableList = { rows: PriceTableRow[]; total: number };
export type PriceTableItemRow = {
  id: string;
  price_table_id: string;
  variant_id: string;
  unit_price: number;
  valid_from: string;
  valid_to: string | null;
  status: string;
  sku: string;
  product_name: string;
};
export type PartnerPriceLink = {
  id: string;
  partner_id: string;
  price_table_id: string;
  valid_from: string;
  valid_to: string | null;
  notes: string | null;
  partner_name: string;
};
export type PriceTableDetail = PriceTableRow & {
  items: PriceTableItemRow[];
  partners: PartnerPriceLink[];
};
export type PriceRuleRow = {
  valid_from: string;
  valid_to: string | null;
  notes: string | null;
  table_code: string;
  table_name: string;
  table_from: string;
  table_to: string | null;
};
export type PreviewResult = {
  rows: {
    id: string;
    store_id: string;
    sale_date: string;
    external_order_id: string;
    external_sku: string;
    variant_id: string | null;
    quantity: number;
    gross_amount: number;
    shipping_fee: number;
    discount_amount: number;
    platform_fee: number;
    status: string;
  }[];
  sales: number;
  units: number;
  gross: number;
};
export type ReconciliationHistoryRow = {
  action: string;
  created_at: string;
  user_id: string;
  context: Json;
};
