/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConvidarRouteImport } from './routes/convidar'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminOrganizacaoRouteImport } from './routes/_authenticated/admin.organizacao'
import { Route as AuthenticatedAdminPermissoesRouteImport } from './routes/_authenticated/admin.permissoes'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque/index'
import { Route as AuthenticatedEstoqueInventariosRouteImport } from './routes/_authenticated/estoque/inventarios'
import { Route as AuthenticatedEstoqueLocationsRouteImport } from './routes/_authenticated/estoque/locations'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated/estoque/movimentacoes'
import { Route as AuthenticatedEstoqueTerceirosRouteImport } from './routes/_authenticated/estoque/terceiros'
import { Route as AuthenticatedEstoqueTransferenciasRouteImport } from './routes/_authenticated/estoque/transferencias'
import { Route as AuthenticatedProdutosIdRouteImport } from './routes/_authenticated/produtos.$id'
import { Route as ApiCronHealthRouteImport } from './routes/api/cron.health'
import { Route as ApiWebhooksReceiverRouteImport } from './routes/api/webhooks.receiver'
import { Route as AuthenticatedEstoqueInventariosIdRouteImport } from './routes/_authenticated/estoque/inventarios.$id'
import { Route as AuthenticatedEstoqueMovimentacoesIdRouteImport } from './routes/_authenticated/estoque/movimentacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidarRoute = ConvidarRouteImport.update({
  id: '/convidar',
  path: '/convidar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrganizacaoRoute =
  AuthenticatedAdminOrganizacaoRouteImport.update({
    id: '/admin/organizacao',
    path: '/admin/organizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissoesRoute =
  AuthenticatedAdminPermissoesRouteImport.update({
    id: '/admin/permissoes',
    path: '/admin/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueInventariosRoute =
  AuthenticatedEstoqueInventariosRouteImport.update({
    id: '/estoque/inventarios',
    path: '/estoque/inventarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueLocationsRoute =
  AuthenticatedEstoqueLocationsRouteImport.update({
    id: '/estoque/locations',
    path: '/estoque/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/estoque/movimentacoes',
    path: '/estoque/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueTerceirosRoute =
  AuthenticatedEstoqueTerceirosRouteImport.update({
    id: '/estoque/terceiros',
    path: '/estoque/terceiros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueTransferenciasRoute =
  AuthenticatedEstoqueTransferenciasRouteImport.update({
    id: '/estoque/transferencias',
    path: '/estoque/transferencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProdutosIdRoute = AuthenticatedProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProdutosRoute,
} as any)
const ApiCronHealthRoute = ApiCronHealthRouteImport.update({
  id: '/api/cron/health',
  path: '/api/cron/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksReceiverRoute = ApiWebhooksReceiverRouteImport.update({
  id: '/api/webhooks/receiver',
  path: '/api/webhooks/receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstoqueInventariosIdRoute =
  AuthenticatedEstoqueInventariosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEstoqueInventariosRoute,
  } as any)
const AuthenticatedEstoqueMovimentacoesIdRoute =
  AuthenticatedEstoqueMovimentacoesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedEstoqueMovimentacoesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convidar': typeof ConvidarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/organizacao': typeof AuthenticatedAdminOrganizacaoRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/estoque/inventarios': typeof AuthenticatedEstoqueInventariosRouteWithChildren
  '/estoque/locations': typeof AuthenticatedEstoqueLocationsRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRouteWithChildren
  '/estoque/terceiros': typeof AuthenticatedEstoqueTerceirosRoute
  '/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/api/cron/health': typeof ApiCronHealthRoute
  '/api/webhooks/receiver': typeof ApiWebhooksReceiverRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/estoque/inventarios/$id': typeof AuthenticatedEstoqueInventariosIdRoute
  '/estoque/movimentacoes/$id': typeof AuthenticatedEstoqueMovimentacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convidar': typeof ConvidarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/organizacao': typeof AuthenticatedAdminOrganizacaoRoute
  '/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/estoque/inventarios': typeof AuthenticatedEstoqueInventariosRouteWithChildren
  '/estoque/locations': typeof AuthenticatedEstoqueLocationsRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRouteWithChildren
  '/estoque/terceiros': typeof AuthenticatedEstoqueTerceirosRoute
  '/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/api/cron/health': typeof ApiCronHealthRoute
  '/api/webhooks/receiver': typeof ApiWebhooksReceiverRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/estoque/inventarios/$id': typeof AuthenticatedEstoqueInventariosIdRoute
  '/estoque/movimentacoes/$id': typeof AuthenticatedEstoqueMovimentacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/convidar': typeof ConvidarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/organizacao': typeof AuthenticatedAdminOrganizacaoRoute
  '/_authenticated/admin/permissoes': typeof AuthenticatedAdminPermissoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/estoque/inventarios': typeof AuthenticatedEstoqueInventariosRouteWithChildren
  '/_authenticated/estoque/locations': typeof AuthenticatedEstoqueLocationsRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRouteWithChildren
  '/_authenticated/estoque/terceiros': typeof AuthenticatedEstoqueTerceirosRoute
  '/_authenticated/estoque/transferencias': typeof AuthenticatedEstoqueTransferenciasRoute
  '/_authenticated/produtos/$id': typeof AuthenticatedProdutosIdRoute
  '/api/cron/health': typeof ApiCronHealthRoute
  '/api/webhooks/receiver': typeof ApiWebhooksReceiverRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/estoque/inventarios/$id': typeof AuthenticatedEstoqueInventariosIdRoute
  '/_authenticated/estoque/movimentacoes/$id': typeof AuthenticatedEstoqueMovimentacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/convidar'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/perfil'
    | '/produtos'
    | '/admin/auditoria'
    | '/admin/organizacao'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/estoque/inventarios'
    | '/estoque/locations'
    | '/estoque/movimentacoes'
    | '/estoque/terceiros'
    | '/estoque/transferencias'
    | '/produtos/$id'
    | '/api/cron/health'
    | '/api/webhooks/receiver'
    | '/estoque/'
    | '/estoque/inventarios/$id'
    | '/estoque/movimentacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/convidar'
    | '/reset-password'
    | '/dashboard'
    | '/onboarding'
    | '/perfil'
    | '/produtos'
    | '/admin/auditoria'
    | '/admin/organizacao'
    | '/admin/permissoes'
    | '/admin/usuarios'
    | '/estoque/inventarios'
    | '/estoque/locations'
    | '/estoque/movimentacoes'
    | '/estoque/terceiros'
    | '/estoque/transferencias'
    | '/produtos/$id'
    | '/api/cron/health'
    | '/api/webhooks/receiver'
    | '/estoque'
    | '/estoque/inventarios/$id'
    | '/estoque/movimentacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/convidar'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/produtos'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/organizacao'
    | '/_authenticated/admin/permissoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/estoque/inventarios'
    | '/_authenticated/estoque/locations'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/estoque/terceiros'
    | '/_authenticated/estoque/transferencias'
    | '/_authenticated/produtos/$id'
    | '/api/cron/health'
    | '/api/webhooks/receiver'
    | '/_authenticated/estoque/'
    | '/_authenticated/estoque/inventarios/$id'
    | '/_authenticated/estoque/movimentacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConvidarRoute: typeof ConvidarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCronHealthRoute: typeof ApiCronHealthRoute
  ApiWebhooksReceiverRoute: typeof ApiWebhooksReceiverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidar': {
      id: '/convidar'
      path: '/convidar'
      fullPath: '/convidar'
      preLoaderRoute: typeof ConvidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/organizacao': {
      id: '/_authenticated/admin/organizacao'
      path: '/admin/organizacao'
      fullPath: '/admin/organizacao'
      preLoaderRoute: typeof AuthenticatedAdminOrganizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissoes': {
      id: '/_authenticated/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AuthenticatedAdminPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/inventarios': {
      id: '/_authenticated/estoque/inventarios'
      path: '/estoque/inventarios'
      fullPath: '/estoque/inventarios'
      preLoaderRoute: typeof AuthenticatedEstoqueInventariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/locations': {
      id: '/_authenticated/estoque/locations'
      path: '/estoque/locations'
      fullPath: '/estoque/locations'
      preLoaderRoute: typeof AuthenticatedEstoqueLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/terceiros': {
      id: '/_authenticated/estoque/terceiros'
      path: '/estoque/terceiros'
      fullPath: '/estoque/terceiros'
      preLoaderRoute: typeof AuthenticatedEstoqueTerceirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque/transferencias': {
      id: '/_authenticated/estoque/transferencias'
      path: '/estoque/transferencias'
      fullPath: '/estoque/transferencias'
      preLoaderRoute: typeof AuthenticatedEstoqueTransferenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos/$id': {
      id: '/_authenticated/produtos/$id'
      path: '/$id'
      fullPath: '/produtos/$id'
      preLoaderRoute: typeof AuthenticatedProdutosIdRouteImport
      parentRoute: typeof AuthenticatedProdutosRoute
    }
    '/api/cron/health': {
      id: '/api/cron/health'
      path: '/api/cron/health'
      fullPath: '/api/cron/health'
      preLoaderRoute: typeof ApiCronHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/receiver': {
      id: '/api/webhooks/receiver'
      path: '/api/webhooks/receiver'
      fullPath: '/api/webhooks/receiver'
      preLoaderRoute: typeof ApiWebhooksReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estoque/inventarios/$id': {
      id: '/_authenticated/estoque/inventarios/$id'
      path: '/$id'
      fullPath: '/estoque/inventarios/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueInventariosIdRouteImport
      parentRoute: typeof AuthenticatedEstoqueInventariosRoute
    }
    '/_authenticated/estoque/movimentacoes/$id': {
      id: '/_authenticated/estoque/movimentacoes/$id'
      path: '/$id'
      fullPath: '/estoque/movimentacoes/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesIdRouteImport
      parentRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
    }
  }
}

interface AuthenticatedProdutosRouteChildren {
  AuthenticatedProdutosIdRoute: typeof AuthenticatedProdutosIdRoute
}

const AuthenticatedProdutosRouteChildren: AuthenticatedProdutosRouteChildren = {
  AuthenticatedProdutosIdRoute: AuthenticatedProdutosIdRoute,
}

const AuthenticatedProdutosRouteWithChildren =
  AuthenticatedProdutosRoute._addFileChildren(
    AuthenticatedProdutosRouteChildren,
  )

interface AuthenticatedEstoqueInventariosRouteChildren {
  AuthenticatedEstoqueInventariosIdRoute: typeof AuthenticatedEstoqueInventariosIdRoute
}

const AuthenticatedEstoqueInventariosRouteChildren: AuthenticatedEstoqueInventariosRouteChildren =
  {
    AuthenticatedEstoqueInventariosIdRoute:
      AuthenticatedEstoqueInventariosIdRoute,
  }

const AuthenticatedEstoqueInventariosRouteWithChildren =
  AuthenticatedEstoqueInventariosRoute._addFileChildren(
    AuthenticatedEstoqueInventariosRouteChildren,
  )

interface AuthenticatedEstoqueMovimentacoesRouteChildren {
  AuthenticatedEstoqueMovimentacoesIdRoute: typeof AuthenticatedEstoqueMovimentacoesIdRoute
}

const AuthenticatedEstoqueMovimentacoesRouteChildren: AuthenticatedEstoqueMovimentacoesRouteChildren =
  {
    AuthenticatedEstoqueMovimentacoesIdRoute:
      AuthenticatedEstoqueMovimentacoesIdRoute,
  }

const AuthenticatedEstoqueMovimentacoesRouteWithChildren =
  AuthenticatedEstoqueMovimentacoesRoute._addFileChildren(
    AuthenticatedEstoqueMovimentacoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRouteWithChildren
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminOrganizacaoRoute: typeof AuthenticatedAdminOrganizacaoRoute
  AuthenticatedAdminPermissoesRoute: typeof AuthenticatedAdminPermissoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedEstoqueInventariosRoute: typeof AuthenticatedEstoqueInventariosRouteWithChildren
  AuthenticatedEstoqueLocationsRoute: typeof AuthenticatedEstoqueLocationsRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRouteWithChildren
  AuthenticatedEstoqueTerceirosRoute: typeof AuthenticatedEstoqueTerceirosRoute
  AuthenticatedEstoqueTransferenciasRoute: typeof AuthenticatedEstoqueTransferenciasRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRouteWithChildren,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminOrganizacaoRoute: AuthenticatedAdminOrganizacaoRoute,
  AuthenticatedAdminPermissoesRoute: AuthenticatedAdminPermissoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedEstoqueInventariosRoute:
    AuthenticatedEstoqueInventariosRouteWithChildren,
  AuthenticatedEstoqueLocationsRoute: AuthenticatedEstoqueLocationsRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRouteWithChildren,
  AuthenticatedEstoqueTerceirosRoute: AuthenticatedEstoqueTerceirosRoute,
  AuthenticatedEstoqueTransferenciasRoute:
    AuthenticatedEstoqueTransferenciasRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConvidarRoute: ConvidarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCronHealthRoute: ApiCronHealthRoute,
  ApiWebhooksReceiverRoute: ApiWebhooksReceiverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
