export type Field = {key:string;label:string;type?:string;options?:string[];lookup?:string;required?:boolean};
export type Area = {title:string;query:string;save?:string;permission:string;write?:string;fields:Field[];columns:string[]};
const f=(key:string,label:string,more:Partial<Field>={}):Field=>({key,label,...more});
const company=f("company_id","Empresa",{lookup:"companies",required:true});
const name=f("name","Nome",{required:true});
export const areas:Record<string,Area>={
 leads:{title:"Leads",query:"leads",save:"lead",permission:"leads.read",write:"leads.create",fields:[name,f("company_name","Empresa informada"),f("email","E-mail",{type:"email"}),f("phone","Telefone"),f("acquisition_source_id","Origem",{lookup:"sources"}),f("commercial_segment_id","Segmento",{lookup:"segments"}),f("status","Status",{options:["NEW","CONTACT_ATTEMPTED","CONTACTED","QUALIFIED","UNQUALIFIED","ARCHIVED"]}),f("disqualification_reason_id","Motivo de desqualificação",{lookup:"reasons"}),f("processing_purpose","Finalidade do tratamento"),f("notes","Observações")],columns:["name","company_name","email","status"]},
 clientes:{title:"Clientes",query:"customers",save:"customer",permission:"customers.read",write:"customers.create",fields:[company,f("customer_code","Código comercial"),f("commercial_segment_id","Segmento",{lookup:"segments"}),f("acquisition_source_id","Origem",{lookup:"sources"}),f("price_table_id","Tabela de preços",{lookup:"price_tables"}),f("payment_terms_id","Condição de pagamento",{lookup:"payment_terms"})],columns:["customer_code","company_id","commercial_status"]},
 oportunidades:{title:"Oportunidades",query:"opportunities",save:"opportunity",permission:"opportunities.read",write:"opportunities.create",fields:[company,f("title","Título",{required:true}),f("stage_id","Etapa",{lookup:"stages",required:true}),f("primary_contact_id","Contato principal",{lookup:"contacts"}),f("expected_close_date","Previsão de fechamento",{type:"date"}),f("description","Descrição")],columns:["title","company_id","estimated_value","probability","status","expected_close_date"]},
 propostas:{title:"Propostas",query:"quotes",permission:"quotes.read",write:"quotes.create",fields:[company,f("price_table_id","Tabela de preços vigente",{lookup:"price_tables",required:true}),f("primary_contact_id","Contato",{lookup:"contacts"}),f("opportunity_id","Oportunidade",{lookup:"opportunities"}),f("valid_until","Validade",{type:"date",required:true}),f("discount_percent","Desconto %",{type:"number"}),f("freight","Frete estimado (R$)",{type:"number"}),f("tax_amount","Tributos informados (R$)",{type:"number"}),f("notes","Observações")],columns:["quote_number","version","company_id","total","status","valid_until"]},
 atividades:{title:"Atividades",query:"activities",save:"activity",permission:"activities.read",write:"activities.manage",fields:[company,f("lead_id","Lead",{lookup:"leads"}),f("opportunity_id","Oportunidade",{lookup:"opportunities"}),f("subject","Assunto",{required:true}),f("activity_type","Tipo",{options:["CALL","MEETING","EMAIL","WHATSAPP","VISIT","TASK","FOLLOW_UP","NOTE","OTHER"],required:true}),f("scheduled_at","Agendamento",{type:"datetime-local",required:true}),f("description","Descrição"),f("status","Status",{options:["PENDING","COMPLETED","CANCELED"]}),f("outcome","Resultado"),f("reason","Motivo da alteração")],columns:["subject","activity_type","scheduled_at","status"]},
 representantes:{title:"Representantes",query:"representatives",save:"representative",permission:"representatives.read",write:"representatives.manage",fields:[name,f("representative_code","Código",{required:true}),f("representative_type","Tipo",{options:["INTERNAL","EXTERNAL","COMPANY"],required:true}),f("company_id","Empresa de representação",{lookup:"companies"}),f("user_id","Usuário vinculado (opcional)",{lookup:"members"}),f("status","Status",{options:["ACTIVE","INACTIVE"]})],columns:["name","representative_code","representative_type","status"]},
 carteiras:{title:"Carteiras",query:"portfolios",permission:"customers.read",write:"portfolios.manage",fields:[company,f("representative_id","Representante",{lookup:"representatives",required:true}),f("reason","Motivo da atribuição",{required:true})],columns:["company_id","representative_id","started_at","ended_at"]},
};
export const configurations:Record<string,Area>={
 segmentos:{title:"Segmentos",query:"segments",save:"segment",permission:"crm.read",write:"crm.configure",fields:[name],columns:["name"]},
 origens:{title:"Origens",query:"sources",save:"source",permission:"crm.read",write:"crm.configure",fields:[name],columns:["name"]},
 motivos:{title:"Motivos",query:"reasons",save:"reason",permission:"crm.read",write:"crm.configure",fields:[name,f("kind","Finalidade",{options:["LEAD","LOSS"],required:true})],columns:["name","kind"]},
 etiquetas:{title:"Etiquetas",query:"tags",save:"tag",permission:"customers.read",write:"crm.configure",fields:[name],columns:["name"]},
 territorios:{title:"Territórios",query:"territories",save:"territory",permission:"representatives.read",write:"crm.configure",fields:[name,f("region","Região"),f("state","UF"),f("city","Cidade"),f("segment_id","Segmento",{lookup:"segments"})],columns:["name","region","state","city"]},
 condicoes:{title:"Condições de pagamento",query:"payment_terms",save:"payment_terms",permission:"crm.read",write:"crm.configure",fields:[name,f("description","Condições acordadas",{required:true})],columns:["name","description"]},
 pipelines:{title:"Pipelines",query:"pipelines",save:"pipeline",permission:"opportunities.read",write:"crm.configure",fields:[name],columns:["name","status"]},
 etapas:{title:"Etapas",query:"stages",save:"stage",permission:"opportunities.read",write:"crm.configure",fields:[name,f("pipeline_id","Pipeline",{lookup:"pipelines",required:true}),f("position","Ordem",{type:"number",required:true}),f("probability","Probabilidade %",{type:"number",required:true})],columns:["name","position","probability"]},
 alcadas:{title:"Alçadas de desconto",query:"authorities",save:"discount_authority",permission:"commercial_sensitive.read",write:"crm.configure",fields:[f("user_id","Aprovador",{lookup:"members",required:true}),f("max_discount_percent","Desconto máximo %",{type:"number",required:true}),f("reason","Motivo",{required:true})],columns:["user_id","max_discount_percent"]},
 comissoes:{title:"Planos de comissão",query:"commission_plans",save:"commission_plan",permission:"commercial_sensitive.read",write:"crm.configure",fields:[name,f("trigger_event","Fato gerador futuro",{options:["SALE_CONFIRMED","RECEIPT_CONFIRMED"],required:true})],columns:["name","trigger_event"]},
 regras:{title:"Regras de comissão estimada",query:"commission_rules",save:"commission_rule",permission:"commercial_sensitive.read",write:"crm.configure",fields:[f("plan_id","Plano",{lookup:"commission_plans",required:true}),f("representative_id","Representante",{lookup:"representatives"}),f("company_id","Cliente",{lookup:"companies"}),f("variant_id","Variante",{lookup:"variants"}),f("rate_type","Método",{options:["PERCENT","FIXED_PER_UNIT"],required:true}),f("rate","Taxa ou valor",{type:"number",required:true}),f("effective_from","Vigência inicial",{type:"date",required:true}),f("effective_to","Vigência final",{type:"date"})],columns:["rate_type","rate","effective_from","effective_to"]},
};
export const labels:Record<string,string>=Object.fromEntries([...Object.values(areas),...Object.values(configurations)].flatMap(a=>a.fields.map(f=>[f.key,f.label])));
Object.assign(labels,{company_id:"Empresa",estimated_value:"Valor estimado",quote_number:"Número",version:"Versão",total:"Total",customer_code:"Código",commercial_status:"Status comercial",started_at:"Início",ended_at:"Fim",probability:"Probabilidade %",representative_id:"Representante",created_at:"Registro"});
